[project]
name = "fastapi-template-v1"
version = "0.1.0"
description = "FastAPI template"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aioboto3>=15.1.0",
    "alembic>=1.16.5",
    "asyncpg>=0.30.0",
    "celery>=5.5.3",
    "decouplet>=0.1.4",
    "dishka>=1.6.0",
    "email-validator>=2.3.0",
    "fastapi>=0.116.1",
    "httpx>=0.28.1",
    "pydantic-settings>=2.6.0",
    "opentelemetry-api>=1.36.0",
    "opentelemetry-sdk>=1.36.0",
    "prometheus-client>=0.22.1",
    "punq>=0.7.0",
    "redis>=6.4.0",
    "sqlalchemy[asyncio]>=2.0.43",
    "psycopg2-binary>=2.9.9",
    "uvicorn[standard]>=0.35.0",
    "PyJWT>=2.9.0",
    "sentry-sdk>=2.0.0",
]

[dependency-groups]
dev = [
    "bandit>=1.8.6",
    "Babel>=2.15.0",
    "invoke>=2.2.0",
    "black>=25.1.0",
    "mypy>=1.17.1",
    "pip-audit>=2.9.0",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "pytest-cov>=6.2.1",
    "pytest-asyncio>=0.23.8",
    "ruff>=0.12.12",
    "import-linter>=2.0.0",
    "types-redis>=4.6.0.20241004",
    "testcontainers>=4.8.1",
]


[tool.black]
line-length = 100
target-version = ["py312"]

[tool.ruff]
line-length = 100
target-version = "py312"
extend-select = ["I", "B", "C4", "T20", "UP"]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["app", "apps"]
combine-as-imports = true

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true
warn_return_any = true
warn_unused_ignores = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
strict_equality = true
exclude = [
    "src/app/core/infra/adapters/db/sqlalchemy/alembic/",
]
mypy_path = ["src"]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["src"]
pythonpath = ["src"]
filterwarnings = [
  "ignore::DeprecationWarning",
]

[tool.bandit]
skips = ["B101"]


