"""Autogenerated i18n stubs. Do not edit manually."""
from gettext import gettext as _


_("conflict")
_("external_api_error")
_("external_http_error")
_("external_network_error")
_("external_service_error")
_("invalid")
_("not_found")
_("resource_not_found")
_("user_exists")
_("validation_failed")
_("internal_error")
