
import ast
import json
from pathlib import Path
from typing import Iterable, List, Optional, Set

PROJECT_ROOT = Path(__file__).resolve().parents[3]
SRC_ROOT = PROJECT_ROOT / "src"
DEFAULT_LOCALES_DIR = PROJECT_ROOT / "src/infra/i18n/locales"
DEFAULT_REGISTRY_PATH = DEFAULT_LOCALES_DIR / ".i18n_keys.json"
# Keep stubs within src so Babel and runtime imports are consistent
DEFAULT_STUB_PATH = PROJECT_ROOT / "src/infra/i18n/locales/i18n_stubs.py"


class _ErrorKeyCollector(ast.NodeVisitor):
    def __init__(self, base_names: Iterable[str]) -> None:
        self._base_names: Set[str] = set(base_names)
        self.keys: Set[str] = set()

    def visit_ClassDef(self, node: ast.ClassDef) -> None:  # noqa: D401
        bases = {self._base_name(base) for base in node.bases}
        bases.discard(None)
        if bases & self._base_names:
            self._base_names.add(node.name)
            for stmt in node.body:
                if isinstance(stmt, ast.Assign):
                    for target in stmt.targets:
                        if isinstance(target, ast.Name) and target.id in {"message_key", "detail_key"}:
                            value = self._constant_value(stmt.value)
                            if value:
                                self.keys.add(value)
        self.generic_visit(node)

    @staticmethod
    def _base_name(expr: ast.expr) -> Optional[str]:
        if isinstance(expr, ast.Name):
            return expr.id
        if isinstance(expr, ast.Attribute):
            return expr.attr
        return None

    @staticmethod
    def _constant_value(node: ast.AST) -> Optional[str]:
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            return node.value
        return None


def collect_error_keys(source_root: Path = SRC_ROOT) -> List[str]:
    collector = _ErrorKeyCollector({"BaseError"})
    for path in source_root.rglob("*.py"):
        try:
            source = path.read_text(encoding="utf-8")
            tree = ast.parse(source, filename=str(path))
        except (UnicodeDecodeError, SyntaxError):
            continue
        collector.visit(tree)
    keys = sorted({*collector.keys, "validation_failed", "invalid"})
    return keys


def write_registry(keys: Iterable[str], path: Path = DEFAULT_REGISTRY_PATH) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    data = sorted(dict.fromkeys(keys))  # preserve unique order
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return path


def load_registry(path: Path = DEFAULT_REGISTRY_PATH) -> List[str]:
    if not path.exists():
        return []
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError(f"Registry {path} must contain a list of keys.")
    return [str(item) for item in data]


def generate_stub(keys: Iterable[str], path: Path = DEFAULT_STUB_PATH) -> Path:
    header = '''"""Autogenerated i18n stubs. Do not edit manually."""
from gettext import gettext as _


'''
    body = "".join(f"_({json.dumps(key)})\n" for key in keys)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(header + body, encoding="utf-8")
    return path


def iter_po_files(locales_dir: Path = DEFAULT_LOCALES_DIR) -> Iterable[Path]:
    for path in locales_dir.glob("**/*.po"):
        yield path


def verify_translations(locales_dir: Path = DEFAULT_LOCALES_DIR) -> List[str]:
    errors: List[str] = []
    for po_file in iter_po_files(locales_dir):
        current_msgid: Optional[str] = None
        for line in po_file.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if stripped.startswith("msgid "):
                current_msgid = stripped.split(" ", 1)[1].strip()
            elif stripped.startswith("msgstr "):
                if current_msgid and current_msgid != '""' and stripped == 'msgstr ""':
                    errors.append(f"{po_file}: missing translation for {current_msgid}")
    return errors


__all__ = [
    "PROJECT_ROOT",
    "SRC_ROOT",
    "DEFAULT_LOCALES_DIR",
    "DEFAULT_REGISTRY_PATH",
    "DEFAULT_STUB_PATH",
    "collect_error_keys",
    "write_registry",
    "load_registry",
    "generate_stub",
    "iter_po_files",
    "verify_translations",
]
